export const FILTERED_POKEMON = 'FILTERED_POKEMON'
export const SEARCH_POKEMON_BEGIN = 'SEARCH_POKEMON_BEGIN'
export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS'
export const SEARCH_POKEMON_FAILURE = 'SEARCH_POKEMON_FAILURE'
export const POKEMON_TYPES = 'POKEMON_TYPES'
export const FETCH_ERROR = 'FETCH_ERROR'

export const LOAD_POKEMON = 'LOAD_POKEMON'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM'

export const GET_ALL_POKEMON = 'GET_ALL_POKEMON'
export const SEARCH_POKEMON = 'SEARCH_POKEMON'

export const GET_POKEMON_BEGIN = 'GET_POKEMON_BEGIN'
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS'
export const GET_POKEMON_ERROR = 'GET_POKEMON_ERROR'
export const GET_DETAIL_POKEMON_BEGIN = 'GET_DETAIL_POKEMON_BEGIN'
export const DETAIL_POKEMON = 'DETAIL_POKEMON'
export const GET_DETAIL_POKEMON_ERROR = 'GET_DETAIL_POKEMON_ERROR'
export const GET_POKEMON_SPECIES_BEGIN = 'GET_POKEMON_SPECIES_BEGIN'
export const POKEMON_SPECIES = 'POKEMON_SPECIES'
export const GET_POKEMON_SPECIES_ERROR = 'GET_POKEMON_SPECIES_ERROR'
export const EVOLUTION_CHAIN = 'EVOLUTION_CHAIN'
export const POKEMON_COLOR = 'POKEMON_COLOR'
export const SHOW_POKEMON_MOVES = 'SHOW_POKEMON_MOVES'

export const UPDATE_FILTER = 'UPDATE_FILTER'
