export const FILTERED_POKEMON = 'FILTERED_POKEMON'
export const SEARCH_POKEMON_BEGIN = 'SEARCH_POKEMON_BEGIN'
export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS'
export const SEARCH_POKEMON_FAILURE = 'SEARCH_POKEMON_FAILURE'
export const POKEMON_TYPES = 'POKEMON_TYPES'
export const FETCH_ERROR = 'FETCH_ERROR'

export const LOAD_POKEMON = 'LOAD_POKEMON'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM'

export const GET_POKEMON_BY_COLOR = 'GET_POKEMON_BY_COLOR'
export const GET_ALL_POKEMON = 'GET_ALL_POKEMON'
export const SEARCH_POKEMON = 'SEARCH_POKEMON'
